version: '3.6'
services:

   cloud-top:
      image: helxplatform/cloudtop:latest
      container_name: cloud-top
      environment:
      volumes:
         - pvc://cloud-top:/usr/local/renci/data
         - pvc://cloud-top:/mounts
      entrypoint: ["bash", "-c", "/init"]
      ports: 
         - 8080:8080
         - 8081:8081
      deploy:
        resources:
          limits:
            cpus: '0.60'
            memory: 5000M
          reservations:
            cpus: '0.60'
            memory: 5000M
   
   #loadortha:
   #   image: helxplatform/loadortha:6
   #   container_name: loadortha
   #   volumes:
   #      - TYCHO_NFS/cloud-top:/user/local/renci/data
   #   entrypoint: /bin/bash /init-pg.sh

   viewer:
      image: ohif/viewer:v1.1.14.3708
      container_name: viewer
      volumes:
         - pvc://cloud-top:/mounts
      environment:
         - MONGO_URL=mongodb://mongo:27017/ohif
         - APP_CONFIG=/mounts/app-config.js
      entrypoint: ["bash", "-c", "sleep 5 && cp /mounts/default.conf /etc/nginx/conf.d && /usr/src/entrypoint.sh nginx -g 'daemon off;'"]
      depends_on:
         - mongo
         - orthanc
      expose:
         - "80"

   orthanc:
      image: jodogne/orthanc-plugins:latest
      container_name: orthanc
      depends_on:
         - postgres
      entrypoint: ["bash", "-c", "sleep 5 && cp /mounts/orthanc.json /etc/orthanc/orthanc.json && Orthanc /etc/orthanc"]
      volumes:
         - pvc://cloud-top:/mounts
      expose:
         - "8042"
         - "4242"
      securityContext:
          privileged: true

   mongo:
      image: mongo:latest
      container_name: mongo
      expose:
         - "27017"
      volumes:
        - pvc://cloud-top:/data/

   postgres:
      # uncommment next/remove following line once built in helxplatform
      # image: helxplatform/postgres:stage
      image: heliumdatastage/postgres:stage
      container_name: postgres
      volumes:
        - pvc://cloud-top:/var/lib/postgresql
      environment:
        - POSTGRES_DB=orthanc
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres-orthanc
      expose:
         - "5432"
      securityContext:
          privileged: true
